### ISSUE TITLE
NameError: name 'raw_input' is not defined

### ISSUE THREAD

**Issue by claudijd** [pwnbus/ansible-vault-diff#11]
$ ./bin/vault_diff
Traceback (most recent call last):
  File "./bin/vault_diff", line 7, in <module>
    repo_name = lib.get_input('Enter repo name: ')
  File "/Users/jclaudius/code/ansible-vault-diff/ansible_vault_diff/lib.py", line 17, in get_input
    return raw_input(msg).rstrip()
NameError: name 'raw_input' is not defined
 (master) $ ./bin/vault_diff
Traceback (most recent call last):
  File "./bin/vault_diff", line 7, in <module>
    repo_name = lib.get_input('Enter repo name: ')
  File "/Users/jclaudius/code/ansible-vault-diff/ansible_vault_diff/lib.py", line 17, in get_input
    return raw_input(msg).rstrip()
NameError: name 'raw_input' is not defined

On Python 3.6.4

**Comment by pwnbus** [comment]
I added support for python3 in https://github.com/pwnbus/ansible-vault-diff/pull/12
